export const STYLE_TOKENS = {
  NeonPop: {
    fontFamily: 'Bangers',
    fontSize: 72,
    color: '#FFFFFF',
    activeColor: '#00FFFF',
    strokeColor: '#000000',
    strokeWidth: 3,
    shadow: '2px 2px 4px rgba(0,0,0,0.8)',
    background: 'transparent',
    animation: 'scale',  // 'scale' | 'fade' | 'slide' | 'bounce' | 'none'
    textTransform: 'uppercase',
    lineHeight: 1.2,
  },
  HinglishFire: {
    fontFamily: 'Anton',
    fontSize: 68,
    color: '#0055FF',
    activeColor: '#FF4400',
    strokeColor: '#000033',
    strokeWidth: 4,
    animation: 'bounce',
    textTransform: 'uppercase',
    lineHeight: 1.2,
  },
  BoldDevanagari: {
    fontFamily: 'Noto Sans Devanagari, Noto Nastaliq Urdu, Noto Sans Arabic, sans-serif',
    fontSize: 64,
    color: '#FFFFFF',
    background: 'rgba(0,0,0,0.5)',
    animation: 'fade',
    textTransform: 'none',
    borderRadius: 8,
    padding: '4px 12px',
    lineHeight: 1.2,
  },
  CleanMinimal: {
    fontFamily: 'Montserrat',
    fontSize: 60,
    color: '#FFFFFF',
    strokeWidth: 2,
    animation: 'fade',
    textTransform: 'none',
    lineHeight: 1.2,
  },
  ReelBold: {
    fontFamily: 'Impact',
    fontSize: 80,
    color: '#FFFFFF',
    strokeWidth: 5,
    animation: 'none',
    textTransform: 'uppercase',
    lineHeight: 1.2,
  }
};
